name: Deploy Long App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26.2'

    - name: Build binary
      run: go build -v -o long-app main.go

    - name: Ensure app directory exists
      run: mkdir -p $HOME/app

    - name: Deploy to app directory
      run: |
        cp long-app $HOME/app/long-app
        chmod +x $HOME/app/long-app

    - name: Restart systemd service
      run: sudo systemctl restart long.service
