# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:
    runs-on: debain-13.4
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26.2'

    - name: Build
      run: go build -v -o app-binary main.go

    # - name: Test
    #   run: go test -v ./...

    # - name: Deploy to Lightsail
    #   uses: appleboy/scp-action@v0.1.7
    #   with:
    #     host: ${{ secrets.LIGHTSAIL_HOST }}
    #     username: ${{ secrets.LIGHTSAIL_USERNAME }}
    #     key: ${{ secrets.LIGHTSAIL_KEY }}
    #     source: "app-binary"
    #     target: "/code/"

    # - name: Restart Application
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.LIGHTSAIL_HOST }}
    #     username: ${{ secrets.LIGHTSAIL_USERNAME }}
    #     key: ${{ secrets.LIGHTSAIL_KEY }}
    #     script: |
    #       chmod +x ~/deploy/app-binary
    #       # Note: This is a basic restart logic. 
    #       # If you use systemd, replace with: sudo systemctl restart your-service-name
    #       pkill app-binary || true
    #       nohup ~/deploy/app-binary > ~/deploy/app.log 2>&1 &
